name: Deploy Next.js to VPS

on:
  push:
    branches:
      - main  # Change this if using another branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 77.37.45.246
          username: root  # Change if using another user
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            # Navigate to project directory
            cd /root/t2h-next  # Change this if your project path is different
            
            # Pull latest code
            git pull origin main
            
            # Install dependencies
            npm install
            
            # Build the project
            npm run build
            
            # Check if the process is already running
            if pm2 list | grep -q "t2h-next"; then
              pm2 reload "t2h-next" --update-env  # Reload if running
            else
              pm2 start "npm run start -- -p 3001" --name "t2h-next"  # Start if not running
            fi